services:
  fitpin-ar:
    container_name: fitpin-ar
    image: ghcr.io/fit-pin/fitpin-ar-backend
    networks:
      fitpin-network:
        ipv4_address: 172.168.0.2

  fitpin-app:
    container_name: fitpin-app
    image: ghcr.io/fit-pin/fitpin-app-backend
    environment:
      - DB_SSH_PRIVATE=${DB_SSH_PRIVATE}
      - APP_APPLICATION_YML=${APP_APPLICATION_YML}
    networks:
      fitpin-network:
        ipv4_address: 172.168.0.3

  fitpin-web:
    container_name: fitpin-web
    image: ghcr.io/fit-pin/fitpin-web-backend
    environment:
      - DB_SSH_PRIVATE=${DB_SSH_PRIVATE}
      - WEB_APPLICATION_YML=${WEB_APPLICATION_YML}
    networks:
      fitpin-network:
        ipv4_address: 172.168.0.4

networks:
  # 네트워크 이름
  fitpin-network:
    ipam:
      config:
        - subnet: 172.168.0.0/16