services:
  fitpin-ar:
    container_name: fitpin-ar
    image: ghcr.io/fit-pin/fitpin-ar-backend
    networks:
      fitpin-network:
        ipv4_address: 172.168.0.2

  fitpin-web:
    container_name: fitpin-web
    image: ghcr.io/fit-pin/fitpin-web-backend
    environment:
      - DB_SSH_PRIVATE=${DB_SSH_PRIVATE}
    networks:
      fitpin-network:
        ipv4_address: 172.168.0.3

networks:
  # 네트워크 이름
  fitpin-network:
    ipam:
      config:
        - subnet: 172.168.0.0/16