name: Publish Docker image

on:
  push:
    branches: 
        - main
  workflow_dispatch:

jobs:
  # fitpin-ar-backend 빌드
  publish_fitpin-ar-backend:
    runs-on: ubuntu-latest
    env:
      PLAT_FORM: linux/amd64,linux/arm64
      IMAGE_NAME: fitpin-ar-backend
      FILE_LOCATION: ./AR-BackEnd/
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTIONS_TOKEN  }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.7.1
        with:
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:master
          platforms: ${{ env.PLAT_FORM }}
        
      - name: Build and push ${{env.IMAGE_NAME}} Docker image
        id: push
        uses: docker/build-push-action@v6.9.0
        with:
          platforms: ${{ env.PLAT_FORM }}
          context: ${{ env.FILE_LOCATION }}
          push: true
          tags: ghcr.io/fit-pin/${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=ghcr.io/fit-pin/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline